version: "3.9"
services:
  node:
    image: ghcr.io/input-output-hk/cardano-node:8.10.0
    command: ["run", "--config", "/config/mainnet.yaml"]
    volumes: ["node-ipc:/ipc", "./config:/config"]
    restart: unless-stopped
    environment:
      - NETWORK=mainnet

  ogmios:
    image: cardanosolutions/ogmios:v6.2.0
    command: ["--node-socket","/ipc/node.socket","--host","0.0.0.0"]
    volumes: ["node-ipc:/ipc"]
    depends_on: [node]
    restart: unless-stopped

  kupo:
    image: cardanosolutions/kupo:v2.10.0
    command: >
      --node-socket /ipc/node.socket
      --host 0.0.0.0 --port 1442
      --since origin
      --match-policy '.*'
      --prune-utxo
      --ogmios http://ogmios:1337
    depends_on: [ogmios]
    volumes: ["kupo-db:/var/lib/kupo","node-ipc:/ipc"]
    restart: unless-stopped

  kupo-sync:
    build: ./kupo-sync
    environment:
      KUPO_URL: http://kupo:1442
      DATABASE_URL: ${DATABASE_URL}
    depends_on: [kupo, postgres]
    restart: unless-stopped
    
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  node-ipc:
  kupo-db:
  postgres-data:
